<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/cadastrar.css">
    <link rel="shortcut icon" href="./img/favicon.ico">
    <title>Starlit</title>
</head>
<body>
     <!--Header-->
 
     <nav class="nav-bar">
        <div class="logo"><a href="/"><img src="./img/logo1.png" alt="Logo" height="55px" width="130px"></a> 
        </div>

        <div class="nav-list"> 
            <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
            </ul>
        </div>

        <div class="mobile-menu-icon">
            <button onclick="menuShow()"><img class="icon menu" src="/img/icon menu.png" alt="" height="30px" width="30px"></button>
        </div>
    </nav>

    <div class="mobile-menu">
        <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
        </ul>
    </div>

    <div class="container">
        <h1>Cadastro</h1>
        <form action="/create" method="post">
            <div class="form-group">
                <label for="nome">Nome:</label>
                <input type="text" id="nome" name="nome" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
            </div>
            <div class="form-group">
                <label for="senha">Senha:</label>
                <input type="password" id="senha" name="senha" required>
            </div>

            <div class="button-container"> 
            <button type="submit" class="btn">Cadastrar</button>
        </div>
        </form>
        <div class="login-link">
            <a href="/login">Já tem login? Faça o login aqui</a>
        </div>
    </div>

<script src="./js/scripts.js"></script>
</body>
</html>