<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/explorar.css">
    <link rel="shortcut icon" href="./img/favicon.ico">
    <title>Starlit</title>
</head>
<body>
 <!--Header-->
 
    <nav class="nav-bar">
        <div class="logo"><a href="/"><img src="/img/logo1.png" alt="Logo" height="55px" width="130px"></a> 
        </div>

        <div class="nav-list"> 
            <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
            </ul>
        </div>

        <div class="mobile-menu-icon">
            <button onclick="menuShow()"><img class="icon menu" src="/img/icon menu.png" alt="" height="30px" width="30px"></button>
        </div>
    </nav>

    <div class="mobile-menu">
        <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
        </ul>
    </div>
    
    <div class="frase">
      <img src="./img/fraseExplorar.png" alt="" width="800px">
    </div>

<!--CANTORES-->
    <div class="Cantores">
    <div class= "cantor1">
        <img src="/img/cantor1.png" alt="" width='350px'>
        <div class="texto">
            <h1>Marcelo Silva</h1>
        <p>Marcelo Silva é um jovem cantor de MPB do Rio de Janeiro, cuja paixão pela música nasceu nas ruas da cidade. Apesar de 
        inicialmente seguir uma carreira convencional, ele eventualmente seguiu seu coração e buscou uma carreira na música. Com uma voz melódica 
        e composições emocionais, Marcelo conquistou um público fiel em pequenos locais. Ele é um defensor 
        da preservação da herança musical brasileira e espera inspirar conexões por meio 
        de sua música. Sua jornada é uma prova de sua dedicação e perseverança em deixar sua marca 
        na cena musical.</p><br>
        <b>Sua jornada é uma prova de sua dedicação e perseverança em deixar sua marca na cena musical.</b><br>
    </div>
  </div>
</div>

<div class="Cantores">
<div class="cantor2">
    <div class="texto">
        <h1>Luna Vesper</h1>
        <p>Luna Vesper é uma cantora de pop alternativo, de 22 anos que nasceu em uma
           pequena cidade em São Paulo. Suas músicas combinam pop melódico com elementos
            experimentais e suas letras profundas refletem introspecção. Com uma voz etérea e 
            presença magnética, ela busca conquistar sua carreira. Luna é conhecida por suas 
            performances imersivas e é uma defensora da expressão criativa e da autenticidade. 
            Sua jornada musical desafia expectativas e redefine os limites do pop alternativo.</p><br>
        <b>Sua jornada musical desafia expectativas e redefine os limites do pop alternativo.</b><br>

    </div>
    <img src="/img/cantor2.png" alt="" width='250px'>
  </div>
</div>

<div class="Cantores">
<div class= "cantor1">
        <img src="/img/cantor3.png" alt="" width='350px'>
        <div class="texto">
            <h1>Jahmar Roots</h1>
        <p>Jahmar Roots é um cantor de reggae nascido na Jamaica, porém crescido 
          no Brasil, cuja paixão pela música começou cedo. Apesar de permanecer 
          desconhecido por muitos anos, sua autenticidade e talento eventualmente
           o levaram a conquistar um público mais amplo. Sua música, impregnada de 
           vibrações positivas e mensagens edificantes, reflete os valores do reggae, 
           usando sua música para promover mudanças sociais positivas em sua comunidade.</p>
    </div>
</div>
</div>

<footer class="footer">
  <p>@starlitfestival</p><br>
  <a href="./Termo de política e privacidade.pdf">Política de Privacidade e Termos de Uso</a><br>
</footer>
<script src="./js/scripts.js"></script>
</body>
</html>