<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="shortcut icon" href="./img/favicon.ico">
    <title>Starlit</title>
</head>
<body>
 <!--Header-->
 
    <nav class="nav-bar">
        <div class="logo"><a href="/"><img src="./img/logo1.png" alt="Logo" height="55px" width="130px"></a> 
        </div>

        <div class="nav-list"> 
            <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
            </ul>
        </div>

        <div class="mobile-menu-icon">
            <button onclick="menuShow()"><img class="icon menu" src="/img/icon menu.png" alt="" height="30px" width="30px"></button>
        </div>
    </nav>

    <div class="mobile-menu">
        <ul>
            <li class="nav-item"> <a href="/explorar" class="nav-link"> Explorar </a></li>
            <li class="nav-item"> <a href="/ingressos" class="nav-link"> Ingressos </a></li>
            <li class="nav-item"> <a href="/login" class="nav-link"> Login </a></li>
        </ul>
    </div>

<!--Escritaa-->
    <div class="frase">
      <img src="/img/Viva o som.png" id="pt1"><br>
      <img src="/img/do amanhã.png" id="pt2">
    </div>

    <!--BANNER-->
    <div class="banner">
      <img src="/img/banner.png" alt="">
    </div>
<footer class="footer">
  <p>@starlitfestival</p><br>
  <a href="./Termo de política e privacidade.pdf">Política de Privacidade e Termos de Uso</a><br>
</footer>

<script src="./js/scripts.js"></script>
 
</body>
</html>